version: "3"
services:
  postgres2:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netology_testdb
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
    - ./postgres_data2:/var/lib/postgresql/data/
    - ./postgres_backup:/tmp/postgres_backup/