version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netology_testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
    - data:/var/lib/postgresql/data/
    - backup:/tmp/postgres_backup/
  pgadmin4:
    image: dpage/pgadmin4:latest
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=protosuv@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    volumes:
    - pgadmin_dir:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/alex/PycharmProjects/Netology-devops/devops-netology/mydocker/Postgres/pgadmin/postgres_backup
  backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/alex/PycharmProjects/Netology-devops/devops-netology/mydocker/Postgres/postgres_data
  pgadmin_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/alex/PycharmProjects/Netology-devops/devops-netology/mydocker/Postgres/pgadmin