---
  - name: Install Java
    hosts: all
    roles:
      - "java"
    tags: Java, ELK

  - name: Install Elasticsearch
    hosts: elasticsearch
    roles:
      - "elastic-role"
    tags: Elasticsearch, ELK

  - name: Install Kibana
    hosts: kibana
    roles:
      - "kibana-role"
    tags: Kibana, ELK 
