FROM centos:7
MAINTAINER Martijn Pepping <martijn.pepping@automiq.nl>

RUN yum update && \
    yum -y install unzip wget && \
    yum -y install openssl python3 texinfo && \
    cd /tmp && mkdir ponysay && \
    wget -O ponysay.zip http://github.com/erkin/ponysay/archive/master.zip && \
    unzip ponysay.zip && cd ponysay-master && \
    ./setup.py install --freedom=partial && \
    yum -y remove openssl texinfo && \
    cd /tmp/ponysay && \
    rm -rf ponysay.zip /ponysay-master /usr/lib/python*/__pycache__/*.pyc /var/cache/apk/*

entrypoint ["/usr/bin/ponysay"]