Vagrant.configure("2") do |config|
  config.vm.define "test_host" do |test_host|

    test_host.vm.box = "bento/ubuntu-20.04"

    test_host.vm.network "private_network", ip: "192.168.10.21"

    test_host.vm.hostname = "test_host"

    test_host.vm.provider :virtualbox do |vb|

      vb.customize ["modifyvm", :id, "--memory", "1024"]

      vb.customize ["modifyvm", :id, "--cpus", "2"]

      end
    test_host.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/my_pc.pub"
    test_host.vm.provision "shell", inline: <<-SHELL

      cat /home/vagrant/.ssh/my_pc.pub >> /home/vagrant/.ssh/authorized_keys

      sudo timedatectl set-timezone Europe/Moscow

      SHELL
    end
