Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04-i386"
    config.vm.provider :virtualbox do |vb|  
	vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
	vb.customize ["modifyvm", :id, "--vtxvpid", "off"]
	vb.customize ["modifyvm", :id, "--paravirtprovider", "none"]
	vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
	vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
	vb.name = "netology_test_vm"
	vb.memory = 1024
	vb.cpus = 1
    end
end
