version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
    volumes:
      - ./Mysql_data:/var/lib/mysql/
      - ./Mysql_backup:/tmp/mysql_backup/
      - ./Mysql_conf:/etc/mysql/conf.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1