version: "3"
services:
  elastic:
    image: protosuv/netology-elastic:v1.1

    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
#    - ./conf/:/tmp/conf/
    - /var/log/elasticsearch:/var/log/elasticsearch
    - /var/lib/elasticsearch:/var/lib/elasticsearch
    - ./snapshots:/usr/share/elasticsearch/snapshots