---
  - name: Install Java
    hosts: all
    roles:
      - "java"
  - name: Install Elasticsearch
    hosts: elastic
    roles:
      - "elastic-role"
  - name: Install Kibana
    hosts: kibana
    roles:
      - "kibana-role"
